name: free_mentor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8

  bcrypt: ^1.1.3

  # State Management
  provider: ^6.0.5

  # Database & Storage
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15  # Updated to match the new dependency
  flutter_secure_storage: ^9.0.0  # Secure user authentication storage
  shared_preferences: ^2.2.2  # Added for local storage

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/serge.jpg
    - assets/images/steven.jpg